app/__init__.py
from flask import Flask

from config import Config

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    # Initialize Flask extensions here

    # Register blueprints here
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.rag import rag_bp
    app.register_blueprint(rag_bp, url_prefix='/rag')

    from app.poc import poc_bp
    app.register_blueprint(poc_bp, url_prefix='/poc')

    @app.route('/test/')
    def test_page():
        return '<h1>Testing the Flask Application Factory Pattern</h1>'

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template
from app.main import bp


@bp.route('/')
def index():
    # return '<h1>Neuromorphic Server Started Successfully...</h1>'
    return render_template('index.html')

app/poc/__init__.py
from flask import Blueprint

poc_bp = Blueprint('poc', __name__)

from app.poc import routes

app/poc/routes.py
from flask import render_template
from app.poc import poc_bp as bp


@bp.route('/')
def index():
    # return '<h1>Neuromorphic Server Started Successfully...</h1>'
    return render_template('poc/index.html')

app/rag/__init__.py
from flask import Blueprint

rag_bp = Blueprint('rag', __name__)


from app.rag import routes

app/rag/controller.py
import os
import numpy as np 

#Local Class
from .utils import SharedUtils



class Akida:
    pass

app/rag/routes.py
from flask import render_template, request, jsonify
from app.rag import rag_bp as bp

#Local Class
from .api import API

@bp.route('/')
def index():
    return render_template('rag/index.html')

# @bp.route('/test_api', methods=['GET'])
# def test_api():
#     name = request.args.get('name')
#     resp= {'status': 'Api working'}
#     return jsonify(resp)

# @bp.route('/snn_predict', methods=['POST'])
# def snn_predict():
#     return API().post__predict_api(request)

# @bp.route('/snn_feature_count', methods=['POST'])
# def snn_feature_count():
#     return API().post__model_feature_count(request)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %} - FlaskApp</title>
    <style>
        h2 {
            width: 100%;
        }

        .title {
            margin: 5px;
            width: 100%;
        }

        .content {
            margin: 5px;
            width: 100%;
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
        }

        .post {
            flex: 20%;
            padding: 10px;
            margin: 5px;
            background-color: #f3f3f3;
            inline-size: 100%;
        }

        .title a {
            color: #00a36f;
            text-decoration: none;
        }

        nav a {
            color: #d64161;
            font-size: 3em;
            margin-left: 50px;
            text-decoration: none;
        }

    </style>
</head>
<body>
    <nav>
        <a href="{{ url_for('main.index') }}">Home</a>
        <a href="{{ url_for('poc.index') }}">POC</a>
        <a href="{{ url_for('rag.index') }}">PDF LLM</a>
        <a href="#">About LLM</a>
        <a href="#">Help</a>
    </nav>
    <hr>
    <div class="content">
        {% block content %} {% endblock %}
    </div>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="content">
        <h2>Server Started Successfully...</h2>
    </div>
{% endblock %}

app/templates/poc/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="content">
        <h2>PDF POC</h2>
    </div>
{% endblock %}

app/templates/rag/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="content">
        <h2>Check your model status here</h2>
    </div>
{% endblock %}